parameter:
  queryApp:
    name: app
    in: query
    required: false
    description: app id
    type: string
  pageSize:
    name: pageSize
    in: query
    required: false
    description: page size
    type: integer
  pageIndex:
    name: pageIndex
    in: query
    required: false
    description: page index
    type: integer
  queryFields:
    name: fields
    in: query
    required: false
    description: select fields to return (partial result)
    type: string
